export const alphabetSounds = {
  a: require("../assets/alphabets/A.mp3"),
  b: require("../assets/alphabets/B.mp3"),
  c: require("../assets/alphabets/C.mp3"),
  d: require("../assets/alphabets/D.mp3"),
  e: require("../assets/alphabets/E.mp3"),
  f: require("../assets/alphabets/F.mp3"),
  g: require("../assets/alphabets/G.mp3"),
  h: require("../assets/alphabets/H.mp3"),
  i: require("../assets/alphabets/I.mp3"),
  j: require("../assets/alphabets/J.mp3"),
  k: require("../assets/alphabets/K.mp3"),
  l: require("../assets/alphabets/L.mp3"),
  m: require("../assets/alphabets/M.mp3"),
  n: require("../assets/alphabets/N.mp3"),
  o: require("../assets/alphabets/O.mp3"),
  p: require("../assets/alphabets/P.mp3"),
  q: require("../assets/alphabets/Q.mp3"),
  r: require("../assets/alphabets/R.mp3"),
  s: require("../assets/alphabets/S.mp3"),
  t: require("../assets/alphabets/T.mp3"),
  u: require("../assets/alphabets/U.mp3"),
  v: require("../assets/alphabets/V.mp3"),
  w: require("../assets/alphabets/W.mp3"),
  x: require("../assets/alphabets/X.mp3"),
  y: require("../assets/alphabets/Y.mp3"),
  z: require("../assets/alphabets/Z.mp3"),
};

export const smallSound = require("../assets/alphabets/small.mp3");

export const numberSounds = {
  0: require("../assets/numbers/0.mp3"),
  1: require("../assets/numbers/1.mp3"),
  2: require("../assets/numbers/2.mp3"),
  3: require("../assets/numbers/3.mp3"),
  4: require("../assets/numbers/4.mp3"),
  5: require("../assets/numbers/5.mp3"),
  6: require("../assets/numbers/6.mp3"),
  7: require("../assets/numbers/7.mp3"),
  8: require("../assets/numbers/8.mp3"),
  9: require("../assets/numbers/9.mp3"),
  10: require("../assets/numbers/10.mp3"),
  11: require("../assets/numbers/11.mp3"),
  12: require("../assets/numbers/12.mp3"),
  13: require("../assets/numbers/13.mp3"),
  14: require("../assets/numbers/14.mp3"),
  15: require("../assets/numbers/15.mp3"),
  16: require("../assets/numbers/16.mp3"),
  17: require("../assets/numbers/17.mp3"),
  18: require("../assets/numbers/18.mp3"),
  19: require("../assets/numbers/19.mp3"),
  20: require("../assets/numbers/20.mp3"),
  30: require("../assets/numbers/30.mp3"),
  40: require("../assets/numbers/40.mp3"),
  50: require("../assets/numbers/50.mp3"),
  60: require("../assets/numbers/60.mp3"),
  70: require("../assets/numbers/70.mp3"),
  80: require("../assets/numbers/80.mp3"),
  90: require("../assets/numbers/90.mp3"),
  100: require("../assets/numbers/100.mp3"),
  1000: require("../assets/numbers/1000.mp3"),
  100000: require("../assets/numbers/lakh.mp3"),
  10000000: require("../assets/numbers/crore.mp3"),
};

export const calendar = {
  month: {
    january: require("../assets/calendar/January.mp3"),
    february: require("../assets/calendar/February.mp3"),
    march: require("../assets/calendar/March.mp3"),
    april: require("../assets/calendar/April.mp3"),
    may: require("../assets/calendar/May.mp3"),
    june: require("../assets/calendar/June.mp3"),
    july: require("../assets/calendar/July.mp3"),
    august: require("../assets/calendar/August.mp3"),
    september: require("../assets/calendar/September.mp3"),
    october: require("../assets/calendar/October.mp3"),
    november: require("../assets/calendar/November.mp3"),
    december: require("../assets/calendar/December.mp3"),
  },

  week: {
    monday: require("../assets/calendar/Monday.mp3"),
    tuesday: require("../assets/calendar/Tuesday.mp3"),
    wednesday: require("../assets/calendar/Wednesday.mp3"),
    thursday: require("../assets/calendar/Thursday.mp3"),
    friday: require("../assets/calendar/Friday.mp3"),
    saturday: require("../assets/calendar/Saturday.mp3"),
    sunday: require("../assets/calendar/Sunday.mp3"),
  },
};
