export const alphabetSounds = {
  a: require("../assets/alphabets/A.mp3"),
  b: require("../assets/alphabets/B.mp3"),
  c: require("../assets/alphabets/C.mp3"),
  d: require("../assets/alphabets/D.mp3"),
  e: require("../assets/alphabets/E.mp3"),
  f: require("../assets/alphabets/F.mp3"),
  g: require("../assets/alphabets/G.mp3"),
  h: require("../assets/alphabets/H.mp3"),
  i: require("../assets/alphabets/I.mp3"),
  j: require("../assets/alphabets/J.mp3"),
  k: require("../assets/alphabets/K.mp3"),
  l: require("../assets/alphabets/L.mp3"),
  m: require("../assets/alphabets/M.mp3"),
  n: require("../assets/alphabets/N.mp3"),
  o: require("../assets/alphabets/O.mp3"),
  p: require("../assets/alphabets/P.mp3"),
  q: require("../assets/alphabets/Q.mp3"),
  r: require("../assets/alphabets/R.mp3"),
  s: require("../assets/alphabets/S.mp3"),
  t: require("../assets/alphabets/T.mp3"),
  u: require("../assets/alphabets/U.mp3"),
  v: require("../assets/alphabets/V.mp3"),
  w: require("../assets/alphabets/W.mp3"),
  x: require("../assets/alphabets/X.mp3"),
  y: require("../assets/alphabets/Y.mp3"),
  z: require("../assets/alphabets/Z.mp3"),
};

export const smallSound = require("../assets/alphabets/small.mp3");
